services:
  - type: worker
    name: whatsapp-bot
    runtime: docker  
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    dockerfilePath: ./Dockerfile  
    dockerCommand: npm start  
    envVars:
      - key: SESSION_ID
        sync: false
      - key: WHATSAPP_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
